// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pixlsuxyyryaihaosntd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpeGxzdXh5eXJ5YWloYW9zbnRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTczMzIsImV4cCI6MjA3Mzk3MzMzMn0.3ORhCLmL9FMQvJYbBWxmEmbulpLaj6MndK-t_yt7S98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});